/Users/andrewlongstaffe/opengrok/apache-tomcat-8.5.9/bin/shutdown.sh
echo Waiting...
sleep 5
echo Starting...
OPENGROK_INSTANCE_BASE=/Users/andrewlongstaffe/opengrok/instance-test /Users/andrewlongstaffe/opengrok/apache-tomcat-8.5.9/bin/startup.sh
